### ISSUE TITLE
derived models update

### ISSUE THREAD

**Issue by WAvdBeek** [openconnectivityfoundation/swagger2doc#14]
when a array of strings is represented in the mapping, then the string in the text is concatinated. no linefeed or even space is added in the generated word table entry.

solution:
add line feed  so that the text corresponds more with the JSON file.

**Comment by marktrayer** [comment]
Please see changes in the following PR:
https://github.com/openconnectivityfoundation/swagger2doc/pull/15

**Comment by WAvdBeek** [comment]
https://github.com/openconnectivityfoundation/swagger2doc/pull/15 accepted
