### ISSUE TITLE
Title population inconsistent for Collections

### ISSUE THREAD

**Issue by marktrayer** [openconnectivityfoundation/swagger2doc#4]
Collections include a "title" Property (it's a Link Parameter).  The code that populates the Title in the Word document sometimes pulls this rather than the Swagger "title" keyword.  Resulting in a need to hand edit the generated file.

**Comment by WAvdBeek** [comment]
fixed, see latest commit

**Comment by marktrayer** [comment]
Tested and verified fixed in commit.
